### ISSUE TITLE
bump plugin error

### ISSUE THREAD

**Issue by phobos2077** [karai17/Simple-Tiled-Implementation#140] opened 2017-02-18 17:21 UTC
After calling bump_init I got the following error:
`lib/sti/plugins/bump.lua:48: attempt to index field 'properties' (a nil value)`

I'm using Tiled 0.18.1 and AFAIK there is no properties for individual tiles, yet the plugin assumes there are.

**Comment by Bobbyjoness** [comment] 2017-02-18 17:23
But properties is how the whole thing has ever worked. Is 0.18.1 a recent release? Maybe something changed.

**Comment by Bobbyjoness** [comment] 2017-02-18 17:25
Weird issue. Seems that STI was updated for tiled 0.18.1.

**Comment by phobos2077** [comment] 2017-02-18 17:30
Ok now I found it in Tiled UI. If Tile in the Tileset has no properties, then there is no "properties" table on export. Need to add a nil check.

**Comment by Bobbyjoness** [comment] 2017-02-18 17:58
Ok. First time someone mentioned it though. Will do it later tonight. Thanks

**Comment by odraencoded** [comment] 2017-02-18 22:48
I just got this error.

How to reproduce: create a tile animation Tiled. Add a single animated tile. Do not add any properties. Export.

It will export a tile with ` id = N, animation = { ... }` but won't have `properties = { ... }` I assume the bump plugin iterates through the tile definitions and it assumed all tile definitions have properties, which isn't true.

The question is: should Bump's plugin check if there is a `properties` entry or should STI add a empty table for `properties` to every tile?

**Comment by Bobbyjoness** [comment] 2017-02-18 22:49
It should check regardless.

**Comment by karai17** [comment] 2017-02-18 22:51
I think this is a bug in Tiled. There should be a properties table, even if it is empty.

@bjorn Thoughts?

**Comment by karai17** [comment] 2017-02-18 22:53
I can add a shim to STI that injects an empty properties table, but that seems like an unpleasant solution.

**Comment by odraencoded** [comment] 2017-02-18 22:56
> I think this is a bug in Tiled. There should be a properties table, even if it is empty.

Tiled doesn't export every tile (every id) to `tilesets[N].tiles`  only those with properties. If a tile has an animation, it exports the animation, but not properties if it doesn't have properties.

It doesn't make sense to export empty property tables because it only makes the exported file needlessly bigger, so it's not a bug with Tiled.

**Comment by phobos2077** [comment] 2017-02-19 09:42
What's the big deal to just add a nil check?

**Comment by bjorn** [comment] 2017-02-20 14:53
I would suggest you just add a condition. I know generally I've been adding values even if they are no different than the default (like 0 rotation, 0 offetx/y, etc.) but tables are somewhat more heavy-weight and I'd rather not fill the file with many empty ones.

It's consistent with `tile.animation`, `tile.terrain` and `tile.objectGroup` (unfortunately violating naming conventions), which are also tables that are left out entirely when not relevant.

**Comment by MIfeanyi** [comment] 2017-03-02 14:09
I experienced this same issue. I added a nil check as @phobos2077 said before line 48 and it also resolved it for me.

**Comment by karai17** [comment] 2017-05-21 03:48
This should be fixed now.

**Closed by karai17** 2017-05-21 03:48 UTC
